### ISSUE TITLE
Unable to detect vlc path under windows7

### ISSUE THREAD

**Issue by ftfniqpl** [feross/vlc-command#10]
node version :10.16.3-x86
vlc version: 3.0.6

console error:
    could not find vlc command path.

**Comment by feross** [comment]
Thanks for reporting this issue. Due to time constraints, I don't have any plans to work on this so I'm going to close it. If you would like to see it implemented, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
